const data={freefire:{title:"Free Fire diamonds",subtitle:"Fast and secure demo purchase",icon:"assets/free-fire-logo.png",packages:[["25 Diamonds",35],["50 Diamonds",50],["115 Diamonds",100],["240 Diamonds",220],["610 Diamonds",550],["1240 Diamonds",1100],["2530 Diamonds",2130],["Weekly Membership",220,"assets/weekly-membership.jpg"],["Monthly Membership",1048,"assets/monthly-membership.jpg"]]},efootball:{title:"eFootball coins & packs",subtitle:"Coins and special packs in NPR",icon:"assets/efootball-logo.png",packages:[["130 Coins",210],["300 Coins",450],["750 Coins",1100],["1040 Coins",1420],["2130 Coins",2900],["3250 Coins",4350],["5700 Coins",7100],["12800 Coins",15150],["Starter Set: Casillas",420,"assets/casillas-pack.png"],["Luis Suarez Pack",200,"assets/suarez-pack.png"]]}};
let selectedGame='freefire',selectedIndex=0,selectedPayment='esewa';
function chooseGame(game){selectedGame=game;selectedIndex=0;render();setTimeout(()=>document.querySelector('#orders').scrollIntoView({behavior:'smooth',block:'start'}),50);}
function render(){const d=data[selectedGame];document.querySelector('#heroFreefireBtn').className=selectedGame==='freefire'?'primary':'secondary';document.querySelector('#heroEfootballBtn').className=selectedGame==='efootball'?'primary':'secondary';document.querySelector('#selectedIcon').innerHTML=`<img src="${d.icon}" alt="" class="mini-logo">`;document.querySelector('#efootballDetails').classList.toggle('hidden',selectedGame!=='efootball');document.querySelector('#freefireDetails').classList.toggle('hidden',selectedGame==='efootball');document.querySelector('#selectedTitle').textContent=d.title;document.querySelector('#selectedSubtitle').textContent=d.subtitle;document.querySelector('#sumGame').textContent=selectedGame==='freefire'?'Free Fire':'eFootball';const box=document.querySelector('#packages');box.innerHTML='';d.packages.forEach((p,i)=>{const b=document.createElement('button');b.className='package'+(i===selectedIndex?' active':'');b.innerHTML=`${p[2]?`<img src="${p[2]}" class="package-icon" alt="">`:''}${p[0]}<b>Rs. ${p[1]}</b>`;b.onclick=()=>{selectedIndex=i;render()};box.appendChild(b)});document.querySelector('#sumPackage').textContent=d.packages[selectedIndex][0];document.querySelector('#sumTotal').textContent='Rs. '+d.packages[selectedIndex][1];}
document.querySelectorAll('.payment').forEach(b=>b.onclick=()=>{selectedPayment=b.dataset.payment;document.querySelectorAll('.payment').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
function showPayment(){if(selectedGame==='freefire' && !document.querySelector('#playerId').value.trim()){alert('Please enter your Free Fire Player ID / UID.');return}if(selectedGame==='efootball' && (!document.querySelector('#konamiId').value.trim() || !document.querySelector('#whatsapp').value.trim())){alert('Please enter your KONAMI User ID and WhatsApp number.');return}const d=data[selectedGame],p=d.packages[selectedIndex];document.querySelector('#modalText').textContent=`${d.title} • ${p[0]}`;document.querySelector('#modalAmount').textContent='Rs. '+p[1];document.querySelector('#modalMethod').textContent=selectedPayment==='esewa'?'eSewa / Khalti / Bank':'Wallet payment';document.querySelector('#paymentModal').classList.remove('hidden')}
function closePayment(){document.querySelector('#paymentModal').classList.add('hidden')}
async function confirmDemo(){
  const d=data[selectedGame], p=d.packages[selectedIndex];
  const userId=selectedGame==='freefire'?document.querySelector('#playerId').value.trim():document.querySelector('#konamiId').value.trim();
  try{
    const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game:selectedGame,product_id:(selectedGame==='freefire'?'ff-':'ef-')+selectedIndex,user_id:userId})});
    const result=await response.json();
    if(!response.ok||result.success===false) throw new Error(result.error||'Order failed');
    alert(result.dry_run?`Test order created: ${result.order.partner_orderid}`:'Order submitted. Check status after payment confirmation.');
    closePayment();
  }catch(error){alert(error.message)}
}
function scrollToSection(id){document.getElementById(id).scrollIntoView({behavior:'smooth'})}
render();