const data={freefire:{title:"Free Fire diamonds",subtitle:"Fast and secure demo purchase",icon:"🔥",packages:[["25 Diamonds",30],["115 Diamonds",110],["240 Diamonds",220],["610 Diamonds",550],["1240 Diamonds",1100],["2530 Diamonds",2100],["5060 Diamonds",4200],["20240 Diamonds",16500]]},efootball:{title:"eFootball coins & packs",subtitle:"Coins and special packs in NPR",icon:"⚽",packages:[["130 Coins",120],["550 Coins",480],["1040 Coins",900],["2130 Coins",1750],["3250 Coins",2600],["Starter Pack",350],["Premium Pack",1100],["Special Pack",2100]]}};
let selectedGame='freefire',selectedIndex=0,selectedPayment='esewa';
function chooseGame(game){selectedGame=game;selectedIndex=0;render();document.querySelector('#orders').scrollIntoView({behavior:'smooth'});}
function render(){const d=data[selectedGame];document.querySelector('#selectedIcon').textContent=d.icon;document.querySelector('#selectedTitle').textContent=d.title;document.querySelector('#selectedSubtitle').textContent=d.subtitle;document.querySelector('#sumGame').textContent=selectedGame==='freefire'?'Free Fire':'eFootball';const box=document.querySelector('#packages');box.innerHTML='';d.packages.forEach((p,i)=>{const b=document.createElement('button');b.className='package'+(i===selectedIndex?' active':'');b.innerHTML=`${p[0]}<b>Rs. ${p[1]}</b>`;b.onclick=()=>{selectedIndex=i;render()};box.appendChild(b)});document.querySelector('#sumPackage').textContent=d.packages[selectedIndex][0];document.querySelector('#sumTotal').textContent='Rs. '+d.packages[selectedIndex][1];}
document.querySelectorAll('.payment').forEach(b=>b.onclick=()=>{selectedPayment=b.dataset.payment;document.querySelectorAll('.payment').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
function showPayment(){if(!document.querySelector('#playerId').value.trim()){alert('Please enter your Player ID / UID.');return}const d=data[selectedGame],p=d.packages[selectedIndex];document.querySelector('#modalText').textContent=`${d.title} • ${p[0]}`;document.querySelector('#modalAmount').textContent='Rs. '+p[1];document.querySelector('#modalMethod').textContent=selectedPayment==='esewa'?'eSewa / Khalti / Bank':'Wallet payment';document.querySelector('#paymentModal').classList.remove('hidden')}
function closePayment(){document.querySelector('#paymentModal').classList.add('hidden')}
function confirmDemo(){alert('Demo order submitted! Connect your backend and payment verification before using this in production.');closePayment()}
function scrollToSection(id){document.getElementById(id).scrollIntoView({behavior:'smooth'})}
render();